cinema_admin:
    resource: "@CinemaAdminBundle/Controller/"
    type:     annotation
    prefix:   /

cinema_cinema:
    resource: "@CinemaCinemaBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
